package com.cxt.crud.dao;

import com.cxt.crud.bean.Employee;
import com.cxt.crud.bean.EmployeeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    long countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    List<Employee> selectByExample(EmployeeExample example);
    List<Employee> selectByExampleWithDept(EmployeeExample example);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    Employee selectByPrimaryKey(Integer empId);
    Employee selectByPrimaryKeyWithDept(Integer empId);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_emp
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    int updateByPrimaryKey(Employee record);
}