package com.cxt.crud.bean;

import org.hibernate.validator.constraints.Email;

import javax.validation.constraints.Pattern;

public class Employee {
    @Override
    public String toString() {
        return "Employee{" +
                "department=" + department +
                ", empId=" + empId +
                ", empName='" + empName + '\'' +
                ", empGender='" + empGender + '\'' +
                ", empEmail='" + empEmail + '\'' +
                ", dId=" + dId +
                '}';
    }

    public Employee(Integer empId, String empName, String empGender, String empEmail, Integer dId) {
        this.empId = empId;
        this.empName = empName;
        this.empGender = empGender;
        this.empEmail = empEmail;
        this.dId = dId;
    }

    public Employee() {
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    private Department department;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.emp_id
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.emp_name
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    //自定义规则
    @Pattern(regexp ="(^[a-zA-Z0-9_-]{3,16}$)|(^[\u2E80-\u9FFF]{2,5})",message="用户名必须字母或数字3-16位 或 2-5位汉字的组合")
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.emp_gender
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    private String empGender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.emp_email
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    @Email(message = "邮箱格式不正确")
    private String empEmail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_emp.d_id
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    private Integer dId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.emp_id
     *
     * @return the value of tbl_emp.emp_id
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.emp_id
     *
     * @param empId the value for tbl_emp.emp_id
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.emp_name
     *
     * @return the value of tbl_emp.emp_name
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.emp_name
     *
     * @param empName the value for tbl_emp.emp_name
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.emp_gender
     *
     * @return the value of tbl_emp.emp_gender
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    public String getEmpGender() {
        return empGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.emp_gender
     *
     * @param empGender the value for tbl_emp.emp_gender
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    public void setEmpGender(String empGender) {
        this.empGender = empGender == null ? null : empGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.emp_email
     *
     * @return the value of tbl_emp.emp_email
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    public String getEmpEmail() {
        return empEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.emp_email
     *
     * @param empEmail the value for tbl_emp.emp_email
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    public void setEmpEmail(String empEmail) {
        this.empEmail = empEmail == null ? null : empEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_emp.d_id
     *
     * @return the value of tbl_emp.d_id
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_emp.d_id
     *
     * @param dId the value for tbl_emp.d_id
     *
     * @mbg.generated Fri Aug 02 11:38:25 GMT+08:00 2019
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }
}